/**
 * Die Klasse enthaelt eine Reihung aller Fussballspieler der EM 2008.
 * Diese Spieler sind in die Hashtabelle einzutragen.
 */
public class Euro2008 {
    public static Player[] allTeamPlayer = {
        new Player("Diego Benaglio", "VfL Wolfsburg"),
        new Player("Pascal Zuberbuehler", "Xamax Neuchatel"),
        new Player("Eldin Jakupovic", "Grasshopper Zuerich"),
        new Player("Valon Behrami", "Lazio Rom"),
        new Player("Philipp Degen", "Borussia Dortmund"),
        new Player("Johan Djourou", "Arsenal London"),
        new Player("Stephane Grichting", "AJ Auxerre"),
        new Player("Stephan Lichtsteiner", "OSC Lille"),
        new Player("Ludovic Magnin", "VfB Stuttgart"),
        new Player("Patrick Mueller", "Olympique Lyon"),
        new Player("Philippe Senderos", "Arsenal London"),
        new Player("Christoph Spycher", "Eintracht Frankfurt"),
        new Player("Tranquillo Barnetta", "Bayer 04 Leverkusen"),
        new Player("Ricardo Cabanas", "Grasshopper Zuerich"),
        new Player("Gelson Fernandes", "Manchester City"),
        new Player("Daniel Gygax", "FC Metz"),
        new Player("Benjamin Huggel", "FC Basel"),
        new Player("Goekhan Inler", "Udinese Calcio"),
        new Player("Hakan Yakin", "Young Boys Bern"),
        new Player("Johan Vonlanthen", "Red Bull Salzburg"),
        new Player("Eren Derdiyok", "FC Basel"),
        new Player("Marco Streller", "FC Basel"),
        new Player("Alexander Frei", "Borussia Dortmund"),
        new Player("Petr Cech", "FC Chelsea"),
        new Player("Jaromir Blazek", "1. FC Nuernberg"),
        new Player("Daniel Zitka", "RSC Anderlecht"),
        new Player("Zdenek Grygera", "Juventus Turin"),
        new Player("Marek Jankulovski", "AC Milan"),
        new Player("Michal Kadlec", "Sparta Prag"),
        new Player("Radoslav Kovac", "Spartak Moskau"),
        new Player("Zdenek Pospech", "FC Kopenhagen"),
        new Player("David Rozehnal", "Lazio Rom"),
        new Player("Tomas Sivok", "Sparta Prag"),
        new Player("Tomas Ujfalusi", "Fiorentina"),
        new Player("Tomas Galasek", "1. FC Nuernberg"),
        new Player("David Jarolim", "Hamburger SV"),
        new Player("Marek Matejovsky", "Reading"),
        new Player("Jaroslav Plasil", "Osasuna"),
        new Player("Jan Polak", "RSC Anderlecht"),
        new Player("Daniel Pudil", "Slavia Prag"),
        new Player("Libor Sionko", "FC Kopenhagen"),
        new Player("Stanislav Vlcek", "RSC Anderlecht"),
        new Player("Milan Baros", "Portsmouth"),
        new Player("Martin Fenin", "Eintracht Frankfurt"),
        new Player("Jan Koller", "1. FC Nuernberg"),
        new Player("Vaclav Sverkos", "FC Ostrava"),
        new Player("Ricardo", "Betis Sevilla"),
        new Player("Quim", "Benfica Lissabon"),
        new Player("Rui Patricio", "Sporting Lissabon"),
        new Player("Ricardo Carvalho", "FC Chelsea"),
        new Player("Pepe", "Real Madrid"),
        new Player("Bruno Alves", "FC Porto"),
        new Player("Fernando Meira", "VfB Stuttgart"),
        new Player("Jose Bosingwa", "FC Porto"),
        new Player("Paulo Ferreira", "FC Chelsea"),
        new Player("Miguel", "Valencia CF"),
        new Player("Jorge Ribeiro", "Boavista Porto"),
        new Player("Petit", "Benfica"),
        new Player("Miguel Veloso", "Sporting Lissabon"),
        new Player("Raul Mereiles", "FC Porto"),
        new Player("Joao Moutinho", "Sporting Lissabon"),
        new Player("Deco", "FC Barcelona"),
        new Player("Cristiano Ronaldo", "Manchester United"),
        new Player("Nani", "Manchester United"),
        new Player("Ricardo Quaresma", "FC Porto"),
        new Player("Simao Sabrosa", "Atletico Madrid"),
        new Player("Nuno Gomes", "Benfica Lissabon"),
        new Player("Hugo Almeida", "Werder Bremen"),
        new Player("Helder Postiga", "Panathinaikos Athen"),
        new Player("Volkan Demirel", "Fenerbahce Istanbul"),
        new Player("Ruestue Recber", "Besiktas Istanbul"),
        new Player("Tolga Zengin", "Trabzonspor"),
        new Player("Ugur Boral", "Fenerbahce Istanbul"),
        new Player("Sabri Sarioglu", "Galatasaray Istanbul"),
        new Player("Servet Cetin", "Galatasaray Istanbul"),
        new Player("Hakan Kadir Balta", "Galatasaray Istanbul"),
        new Player("Emre Guengoer", "Galatasaray Istanbul"),
        new Player("Gokhan Zan", "Besiktas Istanbul"),
        new Player("Emre Asik", "Ankaraspor"),
        new Player("Mehmet Aurelio", "Fenerbahce Istanbul"),
        new Player("Kazim Kazim", "Fenerbahce Istanbul"),
        new Player("Mehmet Topal", "Galatasaray Istanbul"),
        new Player("Ayhan Akman", "Galatasaray Istanbul"),
        new Player("Arda Turan", "Galatasaray Istanbul"),
        new Player("Emre Beloezoglu", "Newcastle United"),
        new Player("Tumer Metin", "Larissa"),
        new Player("Hamit Altintop", "Bayern Muenchen"),
        new Player("Tuncay Sanli", "Middlesbrough"),
        new Player("Goekdeniz Karadeniz", "Rubin Kasan"),
        new Player("Nihat Kahveci", "Villarreal"),
        new Player("Semih Sentuerk", "Fenerbahce Istanbul"),
        new Player("Mevluet Erdinc", "Sochaux"),
        new Player("Alexander Manninger", "AC Siena"),
        new Player("Juergen Macho", "AEK Athen"),
        new Player("Ramazan oezcan", "TSG Hoffenheim 1899"),
        new Player("Martin Stranzl", "Spartak Moskau"),
        new Player("Emanuel Pogatetz", "FC Middlesbrough"),
        new Player("Ronald Gercaliu", "FK Austria Wien"),
        new Player("Markus Katzer", "SK Rapid Wien"),
        new Player("Gyoergy Garics", "SSC Napoli"),
        new Player("Sebastian Proedl", "SK Sturm Graz"),
        new Player("Juergen Patocka", "SK Rapid Wien"),
        new Player("Martin Hiden", "SK Austria Kaernten"),
        new Player("Joachim Standfest", "FK Austria Wien"),
        new Player("Christian Fuchs", "SV Mattersburg"),
        new Player("Rene Aufhauser", "Red Bull Salzburg"),
        new Player("Ivica Vastic", "LASK"),
        new Player("Christoph Leitgeb", "Red Bull Salzburg"),
        new Player("Andreas Ivanschitz", "Panathinaikos Athen"),
        new Player("uemit Korkmaz", "SK Rapid Wien"),
        new Player("Juergen Saeumel", "SK Sturm Graz"),
        new Player("Roland Linz", "SC Braga"),
        new Player("Roman Kienast", "Ham-Kam"),
        new Player("Martin Harnik", "Werder Bremen"),
        new Player("Erwin Hoffer", "SK Rapid Wien"),
        new Player("Stipe Pletikosa", "Spartak Moskau"),
        new Player("Vedran Runje", "RC Lens"),
        new Player("Mario Galinovic", "Panathinaikos"),
        new Player("Vedran Corluka", "Manchester City"),
        new Player("Dario Simic", "AC Milan"),
        new Player("Robert Kovac", "Borussia Dortmund"),
        new Player("Josip Simunic", "Hertha BSC Berlin"),
        new Player("Dario Knezevic", "AS Livorno"),
        new Player("Hrvoje Vejic", "Tom Tomsk"),
        new Player("Danijel Pranjic", "Heerenveen"),
        new Player("Dario Srna", "Schachtjor Donezk"),
        new Player("Niko Kovac", "RB Salzburg"),
        new Player("Luka Modric", "Dinamo Zagreb"),
        new Player("Niko Kranjcar", "Portsmouth"),
        new Player("Jerko Leko", "AS Monaco"),
        new Player("Ivan Rakitic", "Schalke 04"),
        new Player("Ognjen Vukojevic", "Dinamo Zagreb"),
        new Player("Nikola Pokrivac", "AS Monaco"),
        new Player("Mladen Petric", "Borussia Dortmund"),
        new Player("Ivica Olic", "Hamburger SV"),
        new Player("Ivan Klasnic", "Werder Bremen"),
        new Player("Igor Budan", "FC Parma"),
        new Player("Nikola Kalinic", "Hajduk Split"),
        new Player("Jens Lehmann", "Arsenal London"),
        new Player("Robert Enke", "Hannover 96"),
        new Player("Rene Adler", "Bayer 04 Leverkusen"),
        new Player("Arne Friedrich", "Hertha BSC Berlin"),
        new Player("Clemens Fritz", "Werder Bremen"),
        new Player("Marcell Jansen", "Bayern Muenchen"),
        new Player("Philipp Lahm", "Bayern Muenchen"),
        new Player("Per Mertesacker", "Werder Bremen"),
        new Player("Christoph Metzelder", "Real Madrid"),
        new Player("Heiko Westermann", "Schalke 04"),
        new Player("Michael Ballack", "FC Chelsea"),
        new Player("Tim Borowski", "Werder Bremen"),
        new Player("Torsten Frings", "Werder Bremen"),
        new Player("Thomas Hitzlsperger", "VfB Stuttgart"),
        new Player("David Odonkor", "Betis Sevilla"),
        new Player("Simon Rolfes", "Bayer 04 Leverkusen"),
        new Player("Bastian Schweinsteiger", "Bayern Muenchen"),
        new Player("Piotr Trochowski", "Hamburger SV"),
        new Player("Mario Gomez", "VfB Stuttgart"),
        new Player("Miroslav Klose", "Bayern Muenchen"),
        new Player("Kevin Kuranyi", "Schalke 04"),
        new Player("Oliver Neuville", "Borussia Moenchengladbach"),
        new Player("Lukas Podolski", "Bayern Muenchen"),
        new Player("Artur Boruc", "Celtic Glasgow"),
        new Player("Lukasz Fabianski", "Arsenal London"),
        new Player("Tomasz Kuszczak", "Manchester United"),
        new Player("Jacek Bak", "Austria Wien"),
        new Player("Pawel Golanski", "Steaua Bukarest"),
        new Player("Mariusz Jop", "FK Moskau"),
        new Player("Adam Kokoszka", "Wisla Krakau"),
        new Player("Marcin Wasilewski", "RSC Anderlecht"),
        new Player("Jakub Wawrzyniak", "Legia Warschau"),
        new Player("Michal Zewlakow", "Olympiakos Piraeus"),
        new Player("Jakub Blaszczykowski", "Borussia Dortmund"),
        new Player("Dariusz Dudka", "Wisla Krakau"),
        new Player("Lukasz Gargula", "GKS Belchatow"),
        new Player("Roger Guerreiro", "Legia Warschau"),
        new Player("Jacek Krzynowek", "VfL Wolfsburg"),
        new Player("Mariusz Lewandowski", "Schachtjor Donezk"),
        new Player("Rafal Murawski", "Lech Posen"),
        new Player("Michal Pazdan", "Gornik Zabrze"),
        new Player("Wojciech Lobodzinski", "Wisla Krakau"),
        new Player("Marek Saganowski", "Southhampton"),
        new Player("Eusebiusz Smolarek", "Racing Santander"),
        new Player("Tomasz Zahorski", "Gornik Zabrze"),
        new Player("Macej Zurawski", "Larisa"),
        new Player("Edwin van der Sar", "Manchester United"),
        new Player("Maarten Stekelenburg", "Ajax Amsterdam"),
        new Player("Henk Timmer", "Feyenoord Rotterdam"),
        new Player("Wilfred Bouma", "Aston Villa"),
        new Player("Tim de Cler", "Feyenoord Rotterdam"),
        new Player("John Heitinga", "Ajax Amsterdam"),
        new Player("Joris Mathijsen", "Hamburger SV"),
        new Player("Mario Melchiot", "Wigan Athletic"),
        new Player("Andre Ooijer", "Blackburn Rovers"),
        new Player("Ibrahim Afellay", "PSV Eindhoven"),
        new Player("Giovanni van Bronckhorst", "Feyenoord Rotterdam"),
        new Player("Orlando Engelaar", "Twente Enschede"),
        new Player("Nigel de Jong", "Hamburger SV"),
        new Player("Wesley Sneijder", "Real Madrid"),
        new Player("Rafael van der Vaart", "Hamburger SV"),
        new Player("Demy de Zeeuw", "AZ Alkmaar"),
        new Player("Ryan Babel", "FC Liverpool"),
        new Player("Klaas-Jan Huntelaar", "Ajax Amsterdam"),
        new Player("Dirk Kuyt", "FC Liverpool"),
        new Player("Ruud van Nistelrooy", "Real Madrid"),
        new Player("Robin van Persie", "Arsenal London"),
        new Player("Arjen Robben", "Real Madrid"),
        new Player("Jan Vennegoor of Hesselink", "Celtic"),
        new Player("Gianluigi Buffon", "Juventus Turin"),
        new Player("Marco Amelia", "AS Livorno"),
        new Player("Morgan de Sanctis", "FC Sevilla"),
        new Player("Fabio Cannavaro", "Real Madrid"),
        new Player("Giorgio Chiellini", "Juventus Turin"),
        new Player("Fabio Grosso", "Olympique Lyon"),
        new Player("Marco Materazzi", "Inter Mailand"),
        new Player("Christian Panucci", "AS Roma"),
        new Player("Gianluca Zambrotta", "FC Barcelona"),
        new Player("Andrea Barzagli", "Palermo"),
        new Player("Massimo Ambrosini", "AC Milan"),
        new Player("Alberto Aquilani", "AS Roma"),
        new Player("Mauro Camoranesi", "Juventus Turin"),
        new Player("Daniele de Rossi", "AS Roma"),
        new Player("Gennaro Gattuso", "AC Milan"),
        new Player("Simone Perrotta", "AS Roma"),
        new Player("Andrea Pirlo", "AC Milan"),
        new Player("Marco Borriello", "FC Genua"),
        new Player("Antonio Cassano", "Sampdoria Genua"),
        new Player("Alessandro Del Piero", "Juventus Turin"),
        new Player("Antonio di Natale", "Udinese Calcio"),
        new Player("Fabio Quagliarella", "Udinese Calcio"),
        new Player("Luca Toni", "Bayern Muenchen"),
        new Player("Bogdan Lobont", "Dinamo Bukarest"),
        new Player("Marius Popa", "Poli Timisoara"),
        new Player("Eduard Stancioiu", "CFR Cluj"),
        new Player("Cosmin Contra", "Getafe"),
        new Player("Gabriel Tamas", "Auxerre"),
        new Player("Dorin Goian", "Steaua Bukarest"),
        new Player("Cristian Chivu", "Inter Mailand"),
        new Player("Razvan Rat", "Schachtjor Donezk"),
        new Player("Sorin Ghionea", "Steaua Bukarest"),
        new Player("Cristian Sapunaru", "Rapid Bukarest"),
        new Player("Stefan Radu", "Lazio Rom"),
        new Player("Cosmin Moti", "Dinamo Bukarest"),
        new Player("Florentin Petre", "CSKA Sofia"),
        new Player("Razvan Cocis", "Lok Moskau"),
        new Player("Mirel Radoi", "Steaua Bukarest"),
        new Player("Nicolae Dica", "Steaua Bukarest"),
        new Player("Paul Codrea", "AC Siena"),
        new Player("Banel Nicolita", "Steaua Bukarest"),
        new Player("Adrian Cristea", "Dinamo Bukarest"),
        new Player("Adrian Mutu", "Fiorentina"),
        new Player("Ciprian Marica", "VfB Stuttgart"),
        new Player("Daniel Niculae", "Auxerre"),
        new Player("Marius Niculae", "Inverness"),
        new Player("Gregory Coupet", "Olympique Lyon"),
        new Player("Sebastien Frey", "AC Florenz"),
        new Player("Steve Mandanda", "Olympique Marseille"),
        new Player("Eric Abidal", "FC Barcelona"),
        new Player("Jean-Alain Boumsong", "Olympique Lyon"),
        new Player("Francois Clerc", "Olympique Lyon"),
        new Player("Patrice Evra", "Manchester United"),
        new Player("William Gallas", "Arsenal London"),
        new Player("Willy Sagnol", "Bayern Muenchen"),
        new Player("Lilian Thuram", "FC Barcelona"),
        new Player("Sebastien Squillaci", "Olympique Lyon"),
        new Player("Lassana Diarra", "FC Portsmouth"),
        new Player("Claude Makelele", "FC Chelsea"),
        new Player("Franck Ribery", "Bayern Muenchen"),
        new Player("Jeremy Toulalan", "Olympique Lyon"),
        new Player("Patrick Vieira", "Inter Mailand"),
        new Player("Nicolas Anelka", "FC Chelsea"),
        new Player("Karim Benzema", "Olympique Lyon"),
        new Player("Bafetimbi Gomis", "AS St. Etienne"),
        new Player("Thierry Henry", "FC Barcelona"),
        new Player("Florent Malouda", "FC Chelsea"),
        new Player("Sidney Govou", "Olympique Lyon"),
        new Player("Samir Nasri", "Olympique Marseille"),
        new Player("Antonis Nikopolidis", "Olympiakos Piraeus"),
        new Player("Konstantinos Chalkias", "Aris Saloniki"),
        new Player("Alexandros Tzorvas", "OFI Kreta"),
        new Player("Giourkas Seitaridis", "Atletico Madrid"),
        new Player("Christos Patsatzoglou", "Olympiakos Piraeus"),
        new Player("Nikos Spyropoulos", "Panathinaikos Athen"),
        new Player("Traianos Dellas", "AEK Athen"),
        new Player("Loukas Vyntra", "Panathinaikos Athen"),
        new Player("Vassilios Torosidis", "Olympiakos Piraeus"),
        new Player("Sotirios Kyrgiakos", "Eintracht Frankfurt"),
        new Player("Ioannis Goumas", "Panathinaikos Athen"),
        new Player("Paraskevas Antzas", "Olympiakos Piraeus"),
        new Player("Angelos Basinas", "Real Mallorca"),
        new Player("Stylianos Giannakopoulos", "Bolton Wanderers"),
        new Player("Georgios Karagounis", "Panathinaikos Athen"),
        new Player("Ioannis Amanatidis", "Eintracht Frankfurt"),
        new Player("Konstantinos Katsouranis", "Benfica Lissabon"),
        new Player("Alexandros Tziolis", "Panathinaikos Athen"),
        new Player("Georgios Samaras", "Celtic Glasgow"),
        new Player("Angelos Charisteas", "1. FC Nuernberg"),
        new Player("Dimitris Salpingidis", "Panathinaikos Athen"),
        new Player("Theofanis Gekas", "Bayer 04 Leverkusen"),
        new Player("Nikolaos Liberopoulos", "AEK Athen"),
        new Player("Andreas Isaksson", "Manchester City"),
        new Player("Rami Shaaban", "Hammarby"),
        new Player("Johan Wiland", "Elfsborg BK"),
        new Player("Mikael Nilsson", "Panathinaikos Athen"),
        new Player("Olof Mellberg", "Aston Villa"),
        new Player("Petter Hansson", "Stade Rennes"),
        new Player("Fredrik Stoor", "Rosenborg Trondheim"),
        new Player("Daniel Majstorovic", "FC Basel"),
        new Player("Andreas Granqvist", "Helsingborgs IF"),
        new Player("Mikael Dorsin", "CF Cluj"),
        new Player("Niclas Alexandersson", "IFK Goeteborg"),
        new Player("Anders Svensson", "Elfsborg BK"),
        new Player("Fredrik Ljungberg", "West Ham United"),
        new Player("Kim Kaellstroem", "Olympique Lyon"),
        new Player("Sebastian Larsson", "Birmingham City"),
        new Player("Daniel Andersson", "Malmoe FF"),
        new Player("Christian Wilhelmsson", "Deportivo La Coruna"),
        new Player("Tobias Linderoth", "Galatasaray Istanbul"),
        new Player("Zlatan Ibrahimovic", "Inter Mailand"),
        new Player("Johan Elmander", "Toulouse"),
        new Player("Henrik Larsson", "Helsingborgs IF"),
        new Player("Markus Allbaeck", "FC Kopenhagen"),
        new Player("Markus Rosenberg", "Werder Bremen"),
        new Player("Iker Casillas", "Real Madrid"),
        new Player("Pepe Reina", "FC Liverpool"),
        new Player("Andres Palop", "FC Sevilla"),
        new Player("Sergio Ramos", "Real Madrid"),
        new Player("Carles Puyol", "FC Barcelona"),
        new Player("Joan Capdevila", "Villarreal"),
        new Player("Raul Albiol", "Valencia CF"),
        new Player("Carlos Marchena", "Valencia CF"),
        new Player("Fernando Navarro", "Mallorca"),
        new Player("Alvaro Arbeloa", "FC Liverpool"),
        new Player("Juanito Betis", "FC Sevilla"),
        new Player("Francesc Fabregas", "Arsenal London"),
        new Player("Andres Iniesta", "FC Barcelona"),
        new Player("Xavi", "FC Barcelona"),
        new Player("David Silva", "Valencia CF"),
        new Player("Santi Cazorla", "Villarreal"),
        new Player("Xabi Alonso", "FC Liverpool"),
        new Player("Ruben de la Red", "Getafe"),
        new Player("Marcos Senna", "Villarreal"),
        new Player("David Villa", "Valencia CF"),
        new Player("Daniel Guiza", "Mallorca"),
        new Player("Sergio Garcia", "Real Saragossa"),
        new Player("Fernando Torres", "FC Liverpool"),
        new Player("Igor Akinfejew", "ZSKA Moskau"),
        new Player("Wjatscheslaw Malafejew", "Zenit St. Petersburg"),
        new Player("Wladimir Gabulow", "Amkar Perm"),
        new Player("Sergej Ignaschewitsch", "ZSKA Moskau"),
        new Player("Alexej Beresuzki", "ZSKA Moskau"),
        new Player("Wassili Beresuzki", "ZSKA Moskau"),
        new Player("Alexander Anjukow", "Zenit St. Petersburg"),
        new Player("Denis Kolodin", "Dynamo Moskau"),
        new Player("Renat Janbajew", "Lok Moskau"),
        new Player("Dinijar Biljaletdinow", "Lok Moskau"),
        new Player("Dimitri Torbinskij", "Lok Moskau"),
        new Player("Juri Chirkow", "ZSKA Moskau"),
        new Player("Igor Semschow", "Dynamo Moskau"),
        new Player("Wladimir Bystrow", "Spartak Moskau"),
        new Player("Konstantin Syrjanow", "Zenit St. Petersburg"),
        new Player("Roman Schirokow", "Zenit St. Petersburg"),
        new Player("Sergej Semak", "Rubin Kasan"),
        new Player("Andrej Arschawin", "Zenit St. Petersburg"),
        new Player("Pawel Pogrebnjak", "Zenit St. Petersburg"),
        new Player("Roman Pawljutschenko", "Spartak Moskau"),
        new Player("Dimitri Sytschew", "Lok Moskau"),
        new Player("Roman Adamow", "FK Moskau"),
        new Player("Iwan Saenko", "1. FC Nuernberg")
    };
}
